export const SET_SCHOOL_STATS = 'SET_SCHOOL_STATS';
export const SELECT_COURSE = 'SELECT_COURSE';
export const SET_FEATURED_COURSES = 'SET_FEATURED_COURSES';
export const SELECT_EVENT = 'SELECT_EVENT';
